def substring(t, s):
    idx=0
    loc=[]
    while idx <= len(s)-len(t):
        if s.find(t, idx) == -1:
            break
        else:
            loc.append(s.find(t, idx)+1)
            idx = s.find(t, idx) + 1
    for i in loc:
        print i,

substring('AAGGGAAAA', 'GAGAAGAAGGGAACGAAAGCAAGGGAAATCACAAGGGAACCATCGATTACAAGGGAAGACTCAGAAGGGAAAAGGGAAAAGGGAACATAAGGGAATACGAAGGGAAAAAGGGAACAAGGGAAGGACAAGGGAAAAGGGAACGAAGGGAAAAGGGAAAAGGGAAAGATCGAAGGGAATAAGGGAATTTGGTGCAAAAAGGGAACTAAGGGAAAAGGGAAAAGGGAAAAGGGAACAAGGGAACCCTGCATGCATCAAAGGGAAGCGTGAGAAGGGAATAAGGGAACAAGGGAAACGGGATTGAAGGGAAAAAGGGAAAAGGGAAAGTCTAGATTACCAAGGGAAACAAGGGAAAAGGGAAGGAAGGGAAAAGGGAACTTCTGAAGGGAAACGAAGGGAAGGAAGGGAATCGGAAGGGAACCTAAGGGAAAAGGGAACAAGGGAATATTACCTAAGGGAAATGAGGATTTCGAAGGGAAAATTATTCGAAGCAAGGGAAAAGGGAAAAGGGAAAGAAGGGAATGAAGGGAAGAATAAGGGAAGAAGGGAATAAGGGAAATGAAGGGAACTAAGGGAAGCCAAGGGAAAGAAGGGAAGGAAAGGGAATCCTAAGGGAAGCCTGGTGAAGGGAACTTAGGGTTGAAGGGAAGGCAAGGGAATTGTAAGGGAACTAAGGGAAACCACGCATTAAGAGAAAGGGAAAAGGGAAATTACAAGGGAAAAGCGCGCCAAGGGAAAAGGGAAATTAAAGGGAACGGAAGGGAAAAGGGAAGGAAGGGAACGGAAGGGAAGTAAGGGAACAAGGGAAGAAGGGAAGAAGGGAAAAGGGAAATCTCTAAGGGAAACCTAAGGGAAAAAGGGAACACGAAGGGAACAAGTAAGGGAATACCAAGGGAATGATCCAAGGGAACTTCCCGAGAAGGGAACAAGGGAAGGAGAAGGGAAAAGGGAAAAGGGAACGGGAAAGGGAA')