def transcribe(string):
    new_word = ''
    index = 0
    while index < len(string):
        if string[index] != 'T':
            new_word = new_word+string[index]
        else:
            new_word = new_word+'U'
        index = index + 1
    print new_word


#transcribe('ATCATCG')
transcribe('GAGACGTGAGGTCTGTGGCGGGCGATTGTTATATGACGTAGCCCACGGATAGCACGTAACGAGGAAGGGAAGACGACGTCGATGACTCTCCGCAAGGGCCGGCACGCGCGGCCTAGTCAAGATTCTGCGGACCGTGCGGACTACGGATCCGGCCGTGAGCTGTAGGCCGGAAGGTCGGCAACAGACTACGCTGTGCCGATAAACCCCTAAGGCCGCCGACCCGCTGGGCCGATGTGTCAGTTGTAAATGGATTACATGACATTAGGGTTACCTCCGGATGCTTCACTGAGCCACACAGCTCAATCGCCAACTGTGTCACGTTAAACCCTTGCGACTCTCCCGTGCTGATATAAGTAGCGAAATGTTGCAGTGAACAATTTACATGCTCATGTTATTTTTCGCCCCCAGGGTCAAGTGATGTCGTGTTTTCGGGGGGGGGCTCCCGTCTAGGGCAAAAAATGAAAACGTGTAAGCCACGTCCGGCGGAGAGCTCCCGAAAGAGTCTCGATGATGTGATACTGGCGGTGATCGCCTTCCACTCTAAACTGTGGGAGACGACTAGTTGTTTATCTGCAATTCTCCCGATCGAAGGCAAAAGCGGCACAATCTGGGAACGTGGTGGGACGACCAGAGCGCGTTGAACCGCCTGGATGAACTTGGTTGTCATTGGGGAGTATGTTTAAACCGCGGTAGCGCATTAACTCGCTCCCACGACCCTAAGGGAGTTTTTACCCCATAGAGCACGCTGAATCATACCATAATGCAACTGCTTAACGCTCCAGGCCCACGATACCACCGGTGGTACTCCTTTCTCGATTGTCCAATGGGAATAACTCTGCGGGGCGCGTATATATGGTCGAGTACTGTGTCAATTTAGAGGCCCGGGGTTACGCCCCGAGATACCCTGGTCATGACAGTGGTG')


#alternate idea: find indices of Ts and replace with Us