def count(string):
    A=0
    G=0
    C=0
    T=0
    for letter in string:
        if letter == 'A':
            A = A + 1
        elif letter == 'G':
            G = G + 1
        elif letter == 'C':
            C = C + 1
        elif letter == 'T':
            T = T + 1
    print A, C, G, T


def count2(string):
    A = string.count('A')
    C = string.count('C')
    T = string.count('T')
    G = string.count('G')
    print A, C, G, T


count2('CTCATCAGTACACTTCCAGGACTCACGGAGTAACTACAATGACTTCTAGCCGAACTCGCGGTTATCGCTGATTCAAGCTTCAGGCACCCTTGCCGGTCAGATTTCAGTGCTAGAACGTTTGTAAAGGTGGATAAGTCTCGAATCAACAGCGGCACCGTTCAGTCAATCAATCACAGCCTTCGCCCTTGCCACTCTGAGGCGTTGGCGTGTGGCCGAGAACTCCATAAACGCGGCAGCCAAGTTTGCCGCGTGAAGCCTAATTCACCTTGTCGTATTTCATTAAGCTTCCTGAAAGCCCACTGACGTCTGACATACTAGTCTAAGCATGACCAATCGAGGCCCAATCTAGAAGCATGCTGGGTAGACTAATCATGAGGGTCCTCGGCGTAATGATCACTGTAACCACACTGTCCAACCGGAACAACAGTTAACCGCCCCACCCGTTACAAGAGTGCAATGGTCCATTCTGCTTTTTCCGATGTCTTGAAAATCGAGGAGGCCCTGGGAGGACTGGATTTATTGCAGCTCTTATTCGCTCCACGCGTGTCAACCTCAGGTAGCTGTAATTTCACTTTGTCTCATGGATCAAAATTGCGGTCATAATCATGGGTTCGTGGGATACGCGACGTGCCGAATCGACTCTTTATGCGCTGAAAGCCTCCCGTTAATCAACCGCGTGTAGATCCAGTAGCTATCATGACAGCGGGGCGGCCATCACGGAGTGGATTTGGCAGAGAGACATAGGTACTTTAGCTAATTCCAAAGATCATAGGGCCGCTTCGACTTCTTTTGTCGGAACGTACAGTCGGCTCGACTCTTGCCTGATAGATGCCTCTAGGAGTTAGAACCTGCGCTTACCATTACTGAATACTTCGATTGGGCA')