def reverse_complement(string):
    reverse = string[::-1]
    index = 0
    new_word = ''
    while index < len(reverse):
        if reverse[index] == 'A':
           new_word = new_word + 'T'
        elif reverse[index] == 'T':
           new_word = new_word + 'A'
        elif reverse[index] == 'C':
           new_word = new_word + 'G'
        elif reverse[index] == 'G':
           new_word = new_word + 'C'
        index = index + 1
    print new_word

reverse_complement('AGTCGAGATGGGTGTAGTACCTTAGCGCATACGGCGGCTAGCAGTCCGACCCCACGACATCAACATTTGAATGTCAGAGTCGGCCAACTGAGTCATCAGGCAACGGGGATTTTTCCTCAGGTATCAACTGACGTCGAAGCTGCGGTCTAAATTGCGTGCCCGAGTGGAATCTGTGAATCTTAAAGCTGTAACGACAGTCCGACATAAATATTTGAGCCTGTGTGGCCCAATTAGATGTACGAGTCGTCCATAATGGTGTCGTGAACATGCATGAACCCTTTCGCCCACCCCGTCCTTGAACACGCTAGTGCCTTTGGACATAAACTATGGCTTAATCCAGTCGTATCAGAAGTTCCCTTCCATTGAATTCGCATAGCTTCGGGCTGTCCGAATATCATTACTAACACCGGAGTACAGACCGACAACTGGAAGCCGGGAGCAATGCTCCTACTTTCTATCTTTGCCCAGTTCTGTAGAAACAAGGTTCATGGTAGATTTCCTCCGAATTCTCTCGCTTTACTCCTTTGCCTCAGGTCGTGAGGGGGCTTGGCCAATATTGGACGCCATCAGATTTCTCGCTGAATATTCGGCCGAATCTAGAGGGCTTGCAGTCCACAAGCTCCATAGACATAGATCGGTTCAGCAGGCAAGGACGTCTATATTAACGATGAGTCTATTATAAGTCGGTTAGGGCTCCGAGTAGATACTGACGTCAATAAACATCGAACACGAATGAATATAAGAGTTTATAATACAGAGAGCGCGGACGTATCTGCTCGGATGCTCGTGCTCGTTTGGCAGGCTTACCCGGCGCTCCGAAACTATTACTCCTACAAATACGTGTCGAAAATTTAAGCTAGCCCCGAAATAATCTTGACCAGGTCTCAACGTACTCAATAAGGGGAGATTTGAAAGGTCTGACAGCTAGGGTGATTTCATCGTGCGAAGTACGCGGTCCGGCCAACTCCCGTCCAGTAACTTATATTAGC')
